Adding all back end changes
kphillippo/habit-tracker pull request #20
Opened 2024-02-23 19:17 UTC by LysaHannes

2024-02-23 19:26 UTC, kphillippo commented on back-end/models/HabitCheckIn.js
Spelling error: "ChechInTime"

2024-02-23 21:04 UTC, genious97 commented on back-end/models/HabitCheckIn.js
Resolved :smile:

2024-02-24 01:24 UTC, kphillippo approved these changes

2024-02-24 02:01 UTC, zyfeleven requested changes

2024-02-24 02:01 UTC, zyfeleven commented on back-end/controllers/UserController.js
For sign-up requests, the front-end doesn't have "Streak" as part of req.body. Since you already have default Streak=0 in the table, maybe remove the Streak here?

2024-02-24 02:01 UTC, zyfeleven commented on back-end/controllers/UserController.js
hmm.. somehow I'm not commenting to the right line, it's at line 34, `const {FirstName, LastName, Email, Username, Password, Streak} = req.body`

2024-02-24 02:41 UTC, kphillippo approved these changes

2024-02-24 02:42 UTC, merged